# This is a sample configuration file
worker_heartbeat_timeout: 300000

logging:
  level: info

services:
  - module: ../src/lib/index.js
    entrypoint: apiServiceWorker
    conf:
      mwApis:
      - # This is the only required parameter,
        # the URL of you MediaWiki API endpoint.
        # uri: 'https://develop-official.hlpwiki.agileventures.org/api.php'
        uri: 'https://production.hlpwiki.agileventures.org/api.php'
        # The "domain" is used for communication with Visual Editor
        # and RESTBase.  It defaults to the hostname portion of
        # the `uri` property below, but you can manually set it
        # to an arbitrary string.
        # domain: 'localhost'  # optional
        # To specify a proxy (or proxy headers) specific to this prefix
        # (which overrides defaultAPIProxyURI). Alternatively, set `proxy`
        # to `null` to override and force no proxying when a default proxy
        # has been set.
        #proxy:
        #    uri: 'http://my.proxy:1234/'
        #    headers:  # optional
        #        'X-Forwarded-Proto': 'https'

        strictSSL: false